FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma

RUN apk add --no-cache openssl
RUN corepack enable && corepack prepare pnpm@10.22.0 --activate
RUN npm install
RUN npm run prisma:generate

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["npm", "run", "dev"]
